disabled_rules: # rule identifiers to exclude from running
  - line_length
  - force_cast
  - trailing_whitespace
  - todo
included: # paths to include during linting. `--path` is ignored if present.
  - FrostKit
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
file_length:
  warning: 800
  error: 1400
type_body_length:
  warning: 300
  error: 400
function_body_length:
  warning: 80
  error: 120
